# Pod Disruption Budget for Workers
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: neon-workers-pdb
  namespace: neon
  labels:
    app.kubernetes.io/name: neon
    app.kubernetes.io/component: workers
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: neon
      app.kubernetes.io/component: workers
---
# Pod Disruption Budget for Frontend
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: neon-frontend-pdb
  namespace: neon
  labels:
    app.kubernetes.io/name: neon
    app.kubernetes.io/component: frontend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: neon
      app.kubernetes.io/component: frontend
