import { describe, expect, it } from 'vitest'
import {
  getSuiteExportMetadata,
  renderPythonSuiteExport,
  renderTypeScriptSuiteExport,
} from '@/lib/suites/export'
import type { EvalSuite } from '@/lib/types'

function makeSuite(): EvalSuite {
  return {
    id: 'suite-1',
    project_id: 'project-1',
    name: 'Customer Support Suite',
    description: 'Evaluates support flows',
    agent_id: 'support-agent',
    default_scorers: ['tool_selection', 'reasoning'],
    default_min_score: 0.75,
    default_timeout_seconds: 120,
    parallel: true,
    stop_on_failure: false,
    created_at: '2026-03-01T00:00:00.000Z',
    updated_at: '2026-03-01T00:00:00.000Z',
    cases: [
      {
        id: 'case-1',
        suite_id: 'suite-1',
        name: 'Handles refund requests',
        description: 'Should use refund tools and mention confirmation',
        input: { query: 'I want a refund for my order' },
        expected_tools: ['lookup_order', 'process_refund'],
        expected_tool_sequence: ['lookup_order', 'process_refund'],
        expected_output_contains: ['refund', 'processed'],
        expected_output_pattern: 'refund.*processed',
        scorers: ['tool_selection', 'grounding', 'efficiency'],
        scorer_config: null,
        min_score: 0.8,
        tags: ['refund'],
        timeout_seconds: 45,
        created_at: '2026-03-01T00:00:00.000Z',
        updated_at: '2026-03-01T00:00:00.000Z',
      },
    ],
  }
}

describe('suite export rendering', () => {
  it('renders TypeScript export aligned with the local SDK API', () => {
    const output = renderTypeScriptSuiteExport(makeSuite())

    expect(output).toContain(
      "import { contains, defineSuite, defineTest, llmJudge, regex, tokenEfficiencyScorer, toolSelectionScorer } from '@neon/sdk'",
    )
    expect(output).toContain('const test1 = defineTest({')
    expect(output).toContain("toolCalls: [")
    expect(output).toContain('pattern: new RegExp("refund.*processed")')
    expect(output).toContain('"tool_selection": toolSelectionScorer()')
    expect(output).toContain('"efficiency": tokenEfficiencyScorer()')
    expect(output).toContain('export const suite = defineSuite({')
  })

  it('renders Python export against the checked-in SDK surface', () => {
    const output = renderPythonSuiteExport(makeSuite())

    expect(output).toContain('# Generated by Neon suite export.')
    expect(output).toContain('from neon_sdk import define_suite, define_test')
    expect(output).toContain(
      'from neon_sdk.scorers import LLMJudgeConfig, llm_judge, token_efficiency_scorer, tool_selection_scorer',
    )
    expect(output).toContain('suite = define_suite(')
    expect(output).toContain('default_scorers=[')
    expect(output).toContain('"tool_selection"')
    expect(output).toContain('"reasoning"')
    expect(output).toContain('stop_on_failure=False')
    expect(output).toContain('define_test(')
    expect(output).toContain('tool_selection_scorer([')
    expect(output).toContain('"lookup_order"')
    expect(output).toContain('"process_refund"')
    expect(output).toContain('llm_judge(LLMJudgeConfig(')
    expect(output).toContain('expected_tool_sequence=[')
    expect(output).toContain('expected_output_pattern="refund.*processed"')
  })

  it('returns file metadata for both formats', () => {
    expect(getSuiteExportMetadata(makeSuite(), 'typescript')).toEqual({
      filename: 'customer-support-suite.eval.ts',
      contentType: 'application/typescript',
    })
    expect(getSuiteExportMetadata(makeSuite(), 'python')).toEqual({
      filename: 'customer-support-suite.eval.py',
      contentType: 'text/x-python',
    })
  })
})
